#include <stdint.h>

#include "idt.h"

/*
 * Interrupt types
 * ===============
 * -) Exception:
 *      generated by the CPU, includes faults, ...
 * -) Interrupt Request (IRQ)
 *      hardware signal:
 *      1. PIC receives request
 *      2. PIC passes interrupt to cpu
 *      sti / cli works on this type of interrupt only!
 * -) Software interrupts (int):
 *      used to implement syscalls
 * 
 * When interrupt is received, save internal state
 * Then, call Interrupt Service Routine (ISR) (these need to be
 * returned via the iret instruction!) mapped in the
 * Interrupt Descriptor Table (IDT) (which is pointed to by IDTR)
 * Associated number (0 - 255): identify device and cause
 * 
 *  typedef struct {
 *      uint16_t    isr_low;      // The lower 16 bits of the ISR's address
 *	    uint16_t    kernel_cs;    // The GDT segment selector that the CPU will load into CS before calling the ISR
 *	    uint8_t	    ist;          // The IST in the TSS that the CPU will load into RSP; set to zero for now
 *	    uint8_t     attributes;   // Type and attributes; see the IDT page
 *	    uint16_t    isr_mid;      // The higher 16 bits of the lower 32 bits of the ISR's address
 *	    uint32_t    isr_high;     // The higher 32 bits of the ISR's address
 *	    uint32_t    reserved;     // Set to zero
 *  } __attribute__((packed)) idt_entry_t;
*/

typedef struct __attribute__((packed)) {
    uint16_t offset_low;
    uint16_t selector;
    uint8_t ist;
    uint8_t type_attributes;
    uint16_t offset_mid;
    uint32_t offset_high;
    uint32_t reserved;
} idt_descriptor;

struct {
    uint16_t size;
    uint64_t idt_offset;
} __attribute__((packed)) idtr;

// global idt
__attribute__((aligned(16))) idt_descriptor idt[256];

void initIDT(void)
{

}